name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get Draft Release
        uses: cardinalby/git-get-release-action@v1
        id: latest_draft_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          latest: true
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update Changelog
        id: update_changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.ref_name }}
          release-notes: ${{ steps.latest_draft_release.outputs.body }}
      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
      - name: Update Title and Publish Release
        id: publish_release
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.updateRelease({
              draft: false,
              name: '${{ github.ref_name }}',
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.latest_draft_release.outputs.id }},
              tag_name: '${{ github.ref_name }}'
            })
